name: learnxar_app
description: AR-based learning app for data structures

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_unity_widget: ^2022.2.1

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  http: ^1.2.0
  cloud_firestore: ^5.5.2
  shared_preferences: ^2.3.3

  # Image picker for profile photo
  image_picker: ^1.1.2
  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  flutter_timezone: ^5.0.2

  # Audio
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4044C8"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/streak.mp3
    - assets/sounds/badge.mp3
    - assets/icon/

